In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [11]:
import csv
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.neighbors import KNeighborsClassifier # Import KNN Classifier
from sklearn.ensemble import RandomForestClassifier #Import Random Forest Classifier
from sklearn.naive_bayes import GaussianNB #Import Gaussian Naive Bayes model

In [3]:
with open ('/content/drive/My Drive/FYP1/ML_Model_Files/Ml_Model_File.csv','r') as f:      #taggg2 file
  passage=list(csv.reader(f,delimiter=','))
f.close()
X=np.array(passage)
X=X[1:]
np.random.shuffle(X)
Y=X[:,3]
Y1=X[:,3]
X=X[:,0:3]
X1=X[:,0:3]
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

***KNN***

In [5]:
knn = KNeighborsClassifier(n_neighbors=8)
#Train the model using the training sets
knn.fit(x_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(x_test)

#print("Predicted value of: ",x_test,"is: ",y_pred)
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:968: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  estimator=estimator,
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:561: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


Accuracy: 78.23707213462953


***Decision Tree Classifier***

In [7]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 59.09647904582959


***Random Forest Classifier***

In [8]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 77.61620782615799


***Niave Bayes Classifier***

In [10]:
#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
x_train=np.array(x_train).astype(np.float)
gnb.fit(x_train, y_train)

x_test=np.array(x_test).astype(np.float)
#Predict the response for test dataset
y_pred = gnb.predict(x_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 60.019606241320155


***MultiClass SVM***

In [12]:
svclassifier = SVC(kernel='rbf')
svclassifier.fit(x_train, y_train)

SVC()

In [13]:
y_pred = svclassifier.predict(x_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[  34    0   27   25    0    8    1   60    1  302]
 [   0    1   23   49    0    5    0   14    0   63]
 [   4    0 3635  117    0   84    0   27    1  388]
 [   0    0   87  543    0   62    2   42    0   85]
 [   0    0   14   13    1    4    0    1    0    5]
 [   4    0   36   93    0  600    0    8    0    0]
 [   8    0   77   45    0   13    4  241    0  563]
 [  13    1  138  111    0   31    6  282    0  673]
 [   6    0   47   36    0   13    1   12    3   35]
 [  15    0   80   85    0   11    3   84    2 3133]]
              precision    recall  f1-score   support

      Jalsa1       0.40      0.07      0.13       458
      Jalsa2       0.50      0.01      0.01       155
       Qayam       0.87      0.85      0.86      4256
        Qoum       0.49      0.66      0.56       821
          RY       1.00      0.03      0.05        38
        Ruku       0.72      0.81      0.76       741
      Sajda1       0.24      0.00      0.01       951
      Sajda2       0.37      0.22   

In [15]:
cm = confusion_matrix(y_test,y_pred)
accuracy = float(cm.diagonal().sum())/len(y_test)
print("\nAccuracy Of SVM For The Given Dataset : ", accuracy*100)


Accuracy Of SVM For The Given Dataset :  67.28208479699371


***One Class SVM Model***

In [17]:
# one-class svm for imbalanced binary classification
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import OneClassSVM


import csv
import numpy as np
with open ('/content/drive/My Drive/FYP1/OneClass_SVM_auto/uzairOut/Qayam.csv','r') as f:      #taggg2 file
  data=list(csv.reader(f,delimiter=','))
with open ('/content/drive/My Drive/FYP1/OneClass_SVM_auto/uzairOut/uzairQayam.csv','r') as f:      #taggg2 file
  data1=list(csv.reader(f,delimiter=','))


X=np.array(data)
np.random.shuffle(X)
amna=np.array(data1)
np.random.shuffle(amna)

trainX=X[:,0:3]
trainy=X[:,3]

testX=amna[:,0:3]
testy=amna[:,3]

trainy = trainy.astype(int)
testy = testy.astype(int)

# define outlier detection model
model = OneClassSVM(kernel='rbf', gamma='scale', nu=0.01)
# fit on majority class
trainX = trainX[trainy==0]
model.fit(trainX)
# detect outliers in the test set
yhat = model.predict(testX)
# mark inliers 1, outliers -1
testy[testy == 1] = -1
testy[testy == 0] = 1
# calculate score
score = accuracy_score(testy, yhat)*100
print("accuracy is: ", score)


accuracy is:  97.6318622174381
