In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import csv
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.neighbors import KNeighborsClassifier # Import KNN Classifier
from sklearn.ensemble import RandomForestClassifier #Import Random Forest Classifier
from sklearn.naive_bayes import GaussianNB #Import Gaussian Naive Bayes model

***ML MODEL VALIDATION***

In [ ]:
with open ('/content/drive/My Drive/FYP-DATA/Model.csv','r') as f:      #taggg2 file
  passage=list(csv.reader(f,delimiter=','))
f.close()
X=np.array(passage)
X=X[1:]
np.random.shuffle(X)
Y=X[:,4]
Y1=X[:,4]
X=X[:,1:4]
X1=X[:,1:4]
x_train=X
y_train=Y

In [ ]:
with open ('/content/drive/My Drive/FYP-Files/Testing/test.csv','r') as f:      #taggg2 file
  passage=list(csv.reader(f,delimiter=','))
f.close()
X=np.array(passage)
X=X[1:]
np.random.shuffle(X)
Y=X[:,3]
Y1=X[:,3]
X=X[:,0:3]
X1=X[:,0:3]
x_test=X
y_test=Y

In [ ]:
with open ('/content/drive/My Drive/FYP-DATA/Model.csv','r') as f:      #taggg2 file
  passage=list(csv.reader(f,delimiter=','))
f.close()
X=np.array(passage)
X=X[1:]
np.random.shuffle(X)
Y=X[:,4]
Y1=X[:,4]
X=X[:,1:4]
X1=X[:,1:4]
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

***KNN***

In [ ]:
knn = KNeighborsClassifier(n_neighbors=8)
#Train the model using the training sets
knn.fit(x_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(x_test)

#print("Predicted value of: ",x_test,"is: ",y_pred)
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:976: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  estimator=estimator,


Accuracy: 59.726027397260275


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


In [ ]:
import pickle 
pickle.dump(knn,open('/content/drive/My Drive/FYP1/ML_Model_Files/model.pkl','wb'))

FileNotFoundError: ignored

***Decision Tree Classifier***

In [ ]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 53.76712328767124


***Random Forest Classifier***

In [ ]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 63.6986301369863


***Niave Bayes Classifier***

In [ ]:
#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
x_train=np.array(x_train).astype(np.float)
gnb.fit(x_train, y_train)

x_test=np.array(x_test).astype(np.float)
#Predict the response for test dataset
y_pred = gnb.predict(x_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


Accuracy: 45.54794520547945


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


***MultiClass SVM***

***SVM Parameters***

*   C is just a penality level --- if give high value of c (e.g., 1000) means assigning the high penality when model misclassify. we should not give high value because then we have overfitted model and very low value will lead to inderfitting so moderate value btw 0.1 to 100 is normally good. 

In [ ]:
kernel=['linear','rbf','poly', 'sigmoid']
for i in kernel:
  svclassifier = SVC(kernel=i)
  svclassifier.fit(x_train, y_train)
  print("For kernel : ",i)
  print("Accuracy is : ",svclassifier.score(x_test,y_test))

In [ ]:
svclassifier = SVC(kernel='rbf',C=1, gamma=1)
svclassifier.fit(x_train, y_train)

SVC(C=1, gamma=1)

In [ ]:
y_pred = svclassifier.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
labels=['Jalsa', 'Qayam', 'Qoum', 'Ruku','Sajda','Tashahud']
print(confusion_matrix(y_test,y_pred,labels=labels))
print(classification_report(y_test,y_pred))

[[ 28   4  13   4   9  41]
 [  4 421   4   6  12  12]
 [ 16   6  34   1  24   8]
 [  5   2  19  48  79   1]
 [ 79   4   6   3 109  35]
 [ 95   6  11   0  50 261]]
              precision    recall  f1-score   support

       Jalsa       0.12      0.28      0.17        99
       Qayam       0.95      0.92      0.93       459
        Qoum       0.39      0.38      0.39        89
        Ruku       0.77      0.31      0.44       154
       Sajda       0.39      0.46      0.42       236
    Tashahud       0.73      0.62      0.67       423

    accuracy                           0.62      1460
   macro avg       0.56      0.50      0.50      1460
weighted avg       0.69      0.62      0.64      1460



In [ ]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print("Accuracy: ",accuracy_score(y_test,y_pred))
print("F1_score: ",f1_score(y_test, y_pred, average="macro"))
print("Precision: ",precision_score(y_test, y_pred, average="macro"))
print("Recall: ",recall_score(y_test, y_pred, average="macro"))    

Accuracy:  0.6171232876712329
F1_score:  0.5040801316987801
Precision:  0.5588156756818624
Recall:  0.4954393464630246


In [ ]:
import pickle
pickle.dump(svclassifier,open('/content/drive/My Drive/FYP-Files/Model.pkl','wb'))

***Parameter Tuning***

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1, 1, 10, 100, 1000],'gamma': [1, 0.1, 0.01, 0.001, 0.0001],'kernel':['rbf']}
grid=GridSearchCV(SVC(),param_grid)
grid.fit(x_train,y_train)

In [ ]:
print(grid.best_params_)
print(grid.score(x_test,y_test))

{'C': 1, 'gamma': 1, 'kernel': 'rbf'}
0.8132682132682133


***One Class SVM Model***

In [ ]:
# one-class svm for imbalanced binary classification
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import OneClassSVM


import csv
import numpy as np
with open ('/content/drive/My Drive/FYP1/OneClass_SVM_auto/AmnaOut/Sajda.csv','r') as f:      #taggg2 file
  data=list(csv.reader(f,delimiter=','))
with open ('/content/drive/My Drive/FYP1/OneClass_SVM_auto/AmnaOut/amnaSajda.csv','r') as f:      #taggg2 file
  data1=list(csv.reader(f,delimiter=','))


X=np.array(data)
np.random.shuffle(X)
amna=np.array(data1)
np.random.shuffle(amna)

trainX=X[:,0:3]
trainy=X[:,3]
testX=amna[:,0:3]
testy=amna[:,3]

trainy = trainy.astype(int)
testy = testy.astype(int)

# define outlier detection model
model = OneClassSVM(kernel='rbf', gamma='scale',nu=0.001)
# fit on majority class

trainX = trainX[trainy==0]
trainy = trainy[trainy==0]
model.fit(trainX)
# detect outliers in the test set
yhat = model.predict(testX)
# mark inliers 1, outliers -1
testy[testy == 1] = -1
testy[testy == 0] = 1
# calculate score
score = accuracy_score(testy, yhat)
print("accuracy is: ", score*100)
print("precision is: ", precision_score(testy, yhat))
print("recall is: ", recall_score(testy, yhat))
labels=[1,-1]
print(confusion_matrix(testy,yhat,labels=labels))
print(classification_report(testy,yhat))

accuracy is:  96.28099173553719
precision is:  0.9748953974895398
recall is:  0.9872881355932204
[[233   3]
 [  6   0]]
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         6
           1       0.97      0.99      0.98       236

    accuracy                           0.96       242
   macro avg       0.49      0.49      0.49       242
weighted avg       0.95      0.96      0.96       242



In [ ]:
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV
param_grid={'nu':[0.001, 0.01, 0.1, 1],'gamma': ['scale','auto'],'kernel':['rbf']}
grid=GridSearchCV(OneClassSVM(),param_grid,scoring='accuracy')
print(len(trainX),len(trainy))
grid.fit(trainX,trainy)

3901 3901


GridSearchCV(estimator=OneClassSVM(),
             param_grid={'gamma': ['scale', 'auto'], 'kernel': ['rbf'],
                         'nu': [0.001, 0.01, 0.1, 1]},
             scoring='accuracy')

In [ ]:
print(grid.best_params_)
print(grid.score(testX,testy))

{'gamma': 'scale', 'kernel': 'rbf', 'nu': 0.001}
0.9429824561403509
